### ISSUE TITLE
Panther_go

### ISSUE THREAD

**Issue by AngeTKL** [coriell-research/coriell#1]
is it possible to obtain the name of the genes found after overrepresentation analysis with panther and reactome  ? 

Pleas you rhelp will be useful.

**Comment by jcalendo** [comment]
Unfortunately, the panther over representation API doesn't return the actual list of genes that overlap with the returned GO term's gene list so this information cannot be included in the `panther_go` output. 

You could directly search the panther db website and substitute desired GO terms into the following URL: https://pantherdb.org/tools/gxIdsList.do?acc=GO:0060070&reflist=1 ,for example for GO:0060070 - canonical Wnt signaling pathway. 

You could also try to access similar information using R. The GO db used in the org.Hs.eg.db package is older than the version used by panther currently (GO Ontology database DOI: 10.5281/zenodo.10536401 Released 2024-01-17) so you will get a different number of genes overlapping but t could be close enough to be useful.

```
library(org.Hs.eg.db)


# Your gene list
genes <- c(
    "CTNNB1", "ADAM17", "AXIN1", "AXIN2", "CCND2", "CSNK1E", "CTNNB1",
    "CUL1", "DKK1", "DKK4", "DLL1", "DVL2", "FRAT1", "FZD1", "FZD8",
    "GNAI1", "HDAC11", "HDAC2", "HDAC5", "HEY1", "HEY2", "JAG1",
    "JAG2", "KAT2A", "LEF1", "MAML1", "MYC", "NCOR2", "NCSTN",
    "NKD1", "NOTCH1", "NOTCH4", "NUMB", "PPARD", "PSEN2", "PTCH1",
    "RBPJ", "SKP2", "TCF7", "TP53", "WNT1", "WNT5B", "WNT6"
)

# Result of overrep test -- just pick the top GO term to test
result <- panther_go(genes, "9606", "biological_process")

# Returns a 1:many mapping 
go_genes <- AnnotationDbi::select(
  org.Hs.eg.db, 
  keytype = "GO",
  keys = "GO:0060070", 
  columns = "SYMBOL"
  )

# Select any gene, regardless of EVIDENCE, from the returned list
go_genes <- unique(go_genes$SYMBOL)

# Get the overlapping genes
genes_in_list <- intersect(genes, go_genes)
``` 

I hope this helps.

**Comment by AngeTKL** [comment]
Thank you
